vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       programs_images:
           uri_prefix: /images/programs
           upload_destination: '%kernel.project_dir%/public/images/programs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       about_images:
           uri_prefix: /images/about
           upload_destination: '%kernel.project_dir%/public/images/about'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       links_svg:
           uri_prefix: /images/links
           upload_destination: '%kernel.project_dir%/public/images/links'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
